// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import AnyCodable
import Core
import Foundation

/// The type of the image.
public enum DockerImageType: String, Codable, CaseIterable {
    case singer
    case custom
    case airbyte
}
