// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

/// The registry where the image is stored.
public enum DockerRegistry: String, Codable, CaseIterable {
  case dockerhub = "dockerhub"
  case ghcr = "ghcr"
}
