// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct Model: Codable, JSONEncodable {
    public var fullname: String
    public var modelName: String
    public var systemPrompt: String
    public var id: String
    public var provider: String

    public init(fullname: String, modelName: String, systemPrompt: String, id: String, provider: String) {
        self.fullname = fullname
        self.modelName = modelName
        self.systemPrompt = systemPrompt
        self.id = id
        self.provider = provider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fullname
        case modelName
        case systemPrompt
        case id
        case provider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.fullname, forKey: .fullname)
        try container.encode(self.modelName, forKey: .modelName)
        try container.encode(self.systemPrompt, forKey: .systemPrompt)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.provider, forKey: .provider)
    }
}

extension Model: Equatable {
    public static func ==(lhs: Model, rhs: Model) -> Bool {
        lhs.fullname == rhs.fullname &&
            lhs.modelName == rhs.modelName &&
            lhs.systemPrompt == rhs.systemPrompt &&
            lhs.id == rhs.id &&
            lhs.provider == rhs.provider
    }
}

extension Model: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.fullname.hashValue)
        hasher.combine(self.modelName.hashValue)
        hasher.combine(self.systemPrompt.hashValue)
        hasher.combine(self.id.hashValue)
        hasher.combine(self.provider.hashValue)
    }
}
