// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Notifications settings for a task.
public struct Notifications: Codable, JSONEncodable {
    public var email: EmailNotifications

    public init(email: EmailNotifications) {
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.email, forKey: .email)
    }
}

extension Notifications: Equatable {
    public static func ==(lhs: Notifications, rhs: Notifications) -> Bool {
        lhs.email == rhs.email
    }
}

extension Notifications: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.email.hashValue)
    }
}
