// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct RunTaskPayload: Codable, JSONEncodable {
    /// Additional information that will be passed to the created run.
    public var runMetadata: [String: AnyCodable]?

    public init(runMetadata: [String: AnyCodable]? = nil) {
        self.runMetadata = runMetadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case runMetadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.runMetadata, forKey: .runMetadata)
    }
}

extension RunTaskPayload: Equatable {
    public static func ==(lhs: RunTaskPayload, rhs: RunTaskPayload) -> Bool {
        lhs.runMetadata == rhs.runMetadata
    }
}

extension RunTaskPayload: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.runMetadata?.hashValue)
    }
}
