// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Task runs continuously.
public enum StreamingTriggerType: String, Codable, CaseIterable {
    case streaming
}

extension StreamingTriggerType: Hashable {}
