// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

/// The response from the API after a task update.
public struct TaskUpdateResponse: Codable, JSONEncodable, Hashable {
    /// The task UUID.
    public var taskID: String
    /// Date of last update (RFC3339 format).
    public var updatedAt: String

    public init(taskID: String, updatedAt: String) {
        self.taskID = taskID
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taskID
        case updatedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.taskID, forKey: .taskID)
        try container.encode(self.updatedAt, forKey: .updatedAt)
    }
}
