// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

// MARK: - TaskCreateResponse

/// The response from the API after a task creation.
public struct TaskCreateResponse: Codable, JSONEncodable, Hashable {
    // MARK: Lifecycle

    public init(taskID: String, createdAt: String) {
        self.taskID = taskID
        self.createdAt = createdAt
    }

    // MARK: Public

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taskID
        case createdAt
    }

    /// The task UUID.
    public var taskID: String
    /// Date of creation (RFC3339 format).
    public var createdAt: String

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.taskID, forKey: .taskID)
        try container.encode(self.createdAt, forKey: .createdAt)
    }
}
