//
// AlternativesAsExact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public enum AlternativesAsExact: String, Codable, CaseIterable {
  case ignoreplurals = "ignorePlurals"
  case singlewordsynonym = "singleWordSynonym"
  case multiwordssynonym = "multiWordsSynonym"
}
