//
// ObjectDataAfterSearch.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public struct ObjectDataAfterSearch: Codable, JSONEncodable, Hashable {

  /** ID of the query that this specific record is attributable to. Used to track purchase events with multiple items originating from different searches. */
  public var queryID: String?
  public var price: Price?
  /** The quantity of the purchased or added-to-cart item. The total value of a purchase is the sum of `quantity` multiplied with the `price` for each purchased item. */
  public var quantity: Int?
  public var discount: Discount?

  public init(
    queryID: String? = nil, price: Price? = nil, quantity: Int? = nil, discount: Discount? = nil
  ) {
    self.queryID = queryID
    self.price = price
    self.quantity = quantity
    self.discount = discount
  }

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case queryID
    case price
    case quantity
    case discount
  }

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(queryID, forKey: .queryID)
    try container.encodeIfPresent(price, forKey: .price)
    try container.encodeIfPresent(quantity, forKey: .quantity)
    try container.encodeIfPresent(discount, forKey: .discount)
  }
}
