//
// QuerySuggestionsConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

/// Query Suggestions configuration.
public struct QuerySuggestionsConfiguration: Codable, JSONEncodable, Hashable {

  /** Algolia indices from which to get the popular searches for query suggestions. */
  public var sourceIndices: [SourceIndex]
  public var languages: Languages?
  /** Patterns to exclude from query suggestions. */
  public var exclude: [String]?
  /** Turn on personalized query suggestions. */
  public var enablePersonalization: Bool? = false
  /** Allow suggestions with special characters. */
  public var allowSpecialCharacters: Bool? = false

  public init(
    sourceIndices: [SourceIndex], languages: Languages? = nil, exclude: [String]? = nil,
    enablePersonalization: Bool? = false, allowSpecialCharacters: Bool? = false
  ) {
    self.sourceIndices = sourceIndices
    self.languages = languages
    self.exclude = exclude
    self.enablePersonalization = enablePersonalization
    self.allowSpecialCharacters = allowSpecialCharacters
  }

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case sourceIndices
    case languages
    case exclude
    case enablePersonalization
    case allowSpecialCharacters
  }

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(sourceIndices, forKey: .sourceIndices)
    try container.encodeIfPresent(languages, forKey: .languages)
    try container.encodeIfPresent(exclude, forKey: .exclude)
    try container.encodeIfPresent(enablePersonalization, forKey: .enablePersonalization)
    try container.encodeIfPresent(allowSpecialCharacters, forKey: .allowSpecialCharacters)
  }
}
