//
// RecommendationsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public enum RecommendationsRequest: Codable, JSONEncodable, Hashable {
  case recommendationsQuery(RecommendationsQuery)
  case trendingFacetsQuery(TrendingFacetsQuery)
  case trendingItemsQuery(TrendingItemsQuery)

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .recommendationsQuery(let value):
      try container.encode(value)
    case .trendingFacetsQuery(let value):
      try container.encode(value)
    case .trendingItemsQuery(let value):
      try container.encode(value)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let value = try? container.decode(RecommendationsQuery.self) {
      self = .recommendationsQuery(value)
    } else if let value = try? container.decode(TrendingFacetsQuery.self) {
      self = .trendingFacetsQuery(value)
    } else if let value = try? container.decode(TrendingItemsQuery.self) {
      self = .trendingItemsQuery(value)
    } else {
      throw DecodingError.typeMismatch(
        Self.Type.self,
        .init(
          codingPath: decoder.codingPath,
          debugDescription: "Unable to decode instance of RecommendationsRequest"))
    }
  }
}
