//
// SortRemainingBy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

/// How to display the remaining items:    - &#x60;count&#x60;: facet count (descending).   - &#x60;alpha&#x60;: alphabetical (ascending).   - &#x60;hidden&#x60;: show only pinned values.
public enum SortRemainingBy: String, Codable, CaseIterable {
  case count = "count"
  case alpha = "alpha"
  case hidden = "hidden"
}
