//
// TypoToleranceEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public enum TypoToleranceEnum: String, Codable, CaseIterable {
  case min = "min"
  case strict = "strict"
}
