//
// ViewEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public enum ViewEvent: String, Codable, CaseIterable {
  case view = "view"
}
