// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Bayesian inference results for this variant metric. Omitted when Bayesian results aren't requested or no Bayesian
/// result is available for this metric. Individual inference fields can be omitted when their values aren't available.
public struct BayesianMetricResult: Codable, JSONEncodable {
    /// Probability that this variant is better than the control.
    public var probabilityToBeBetter: Double?
    /// Lower bound of the 95% credible interval for the relative effect (variant/control minus 1).
    public var relativeEffectCILow: Double?
    /// Upper bound of the 95% credible interval for the relative effect (variant/control minus 1).
    public var relativeEffectCIHigh: Double?
    public var evidence: MetricEvidence?

    public init(
        probabilityToBeBetter: Double? = nil,
        relativeEffectCILow: Double? = nil,
        relativeEffectCIHigh: Double? = nil,
        evidence: MetricEvidence? = nil
    ) {
        self.probabilityToBeBetter = probabilityToBeBetter
        self.relativeEffectCILow = relativeEffectCILow
        self.relativeEffectCIHigh = relativeEffectCIHigh
        self.evidence = evidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case probabilityToBeBetter
        case relativeEffectCILow
        case relativeEffectCIHigh
        case evidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.probabilityToBeBetter, forKey: .probabilityToBeBetter)
        try container.encodeIfPresent(self.relativeEffectCILow, forKey: .relativeEffectCILow)
        try container.encodeIfPresent(self.relativeEffectCIHigh, forKey: .relativeEffectCIHigh)
        try container.encodeIfPresent(self.evidence, forKey: .evidence)
    }
}

extension BayesianMetricResult: Equatable {}

extension BayesianMetricResult: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.probabilityToBeBetter?.hashValue)
        hasher.combine(self.relativeEffectCILow?.hashValue)
        hasher.combine(self.relativeEffectCIHigh?.hashValue)
        hasher.combine(self.evidence?.hashValue)
    }
}
