output: build/doc
# Avoid putting the DocSet within the HTML docs.
# WARNING: The path is relative to the output directory.
docset_path: ../docset
docset_icon: doc/img/icon.png
hide_documentation_coverage: true
skip_undocumented: true
# Avoid putting the current date into the docs (this makes the diff quite noisy).
# TODO: Jazzy does not support putting the Cocoapods version so far.
copyright: "© Copyright 2016 [Algolia](https://www.algolia.com/). All rights reserved."
readme: doc/include/reference.md
custom_categories:
    - name: API Client
      children:
        - Client
        - Index
        - Query
        - BrowseIterator
    - name: Places
      children:
        - PlacesClient
        - PlacesQuery
    - name: Auxiliary types
      children:
        - GeoRect
        - IndexQuery
        - LatLng
        - LibraryVersion
    - name: Errors
      children:
        - HTTPError
        - InvalidJSONError
        - StatusCode
