// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct BaseQuerySuggestionsConfigurationWithIndex: Codable, JSONEncodable, Hashable {
    /** Query Suggestions index name. */
    public var indexName: String

    public init(indexName: String) {
        self.indexName = indexName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case indexName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(indexName, forKey: .indexName)
    }
}
