//
//  Language.swift
//  
//
//  Created by Vladislav Fitc on 12.03.2020.
//

import Foundation

public enum Language: String, Codable {
  case afrikaans = "af"
  case arabic = "ar"
  case azeri = "az"
  case bulgarian = "bg"
  case brunei = "bn"
  case catalan = "ca"
  case czech = "cs"
  case welsh = "cy"
  case danish = "da"
  case german = "de"
  case english = "en"
  case esperanto = "eo"
  case spanish = "es"
  case estonian = "et"
  case basque = "eu"
  case finnish = "fi"
  case faroese = "fo"
  case french = "fr"
  case galician = "gl"
  case hebrew = "he"
  case hindi = "hi"
  case hungarian = "hu"
  case armenian = "hy"
  case indonesian = "id"
  case icelandic = "is"
  case italian = "it"
  case japanese = "ja"
  case georgian = "ka"
  case kazakh = "kk"
  case korean = "ko"
  case kyrgyz = "ky"
  case lithuanian = "lt"
  case maori = "mi"
  case mongolian = "mn"
  case marathi = "mr"
  case malay = "ms"
  case maltese = "mt"
  case norwegian = "nb"
  case dutch = "nl"
  case northernsotho = "ns"
  case polish = "pl"
  case pashto = "ps"
  case portuguese = "pt"
  case quechua = "qu"
  case romanian = "ro"
  case russian = "ru"
  case slovak = "sk"
  case albanian = "sq"
  case swedish = "sv"
  case swahili = "sw"
  case tamil = "ta"
  case telugu = "te"
  case tagalog = "tl"
  case tswana = "tn"
  case turkish = "tr"
  case tatar = "tt"
}
