// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

// MARK: - BaseGetApiKeyResponse

public struct BaseGetApiKeyResponse: Codable, JSONEncodable, Hashable {
    // MARK: Lifecycle

    public init(value: String? = nil, createdAt: Int64) {
        self.value = value
        self.createdAt = createdAt
    }

    // MARK: Public

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case createdAt
    }

    /// API key.
    public var value: String?
    /// Timestamp of creation in milliseconds in [Unix epoch time](https://wikipedia.org/wiki/Unix_time).
    public var createdAt: Int64

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.value, forKey: .value)
        try container.encode(self.createdAt, forKey: .createdAt)
    }
}
