// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import AnyCodable
import Core
import Foundation

public struct Cursor: Codable, JSONEncodable, Hashable {
    /// Cursor to get the next page of the response.  The parameter must match the value returned in the response of a
    /// previous request. The last page of the response does not return a `cursor` attribute.
    public var cursor: String?

    public init(cursor: String? = nil) {
        self.cursor = cursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.cursor, forKey: .cursor)
    }
}
