// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

// MARK: - ListApiKeysResponse

public struct ListApiKeysResponse: Codable, JSONEncodable, Hashable {
    // MARK: Lifecycle

    public init(keys: [GetApiKeyResponse]) {
        self.keys = keys
    }

    // MARK: Public

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keys
    }

    /// API keys.
    public var keys: [GetApiKeyResponse]

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.keys, forKey: .keys)
    }
}
