// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct SearchTimeRange: Codable, JSONEncodable {
    /// When the rule should start to be active, in Unix epoch time.
    public var from: Int64?
    /// When the rule should stop to be active, in Unix epoch time.
    public var until: Int64?

    public init(from: Int64? = nil, until: Int64? = nil) {
        self.from = from
        self.until = until
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case from
        case until
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.from, forKey: .from)
        try container.encodeIfPresent(self.until, forKey: .until)
    }
}

extension SearchTimeRange: Equatable {
    public static func ==(lhs: SearchTimeRange, rhs: SearchTimeRange) -> Bool {
        lhs.from == rhs.from &&
            lhs.until == rhs.until
    }
}

extension SearchTimeRange: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.from?.hashValue)
        hasher.combine(self.until?.hashValue)
    }
}
