// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Settings for the semantic search part of NeuralSearch. Only used when `mode` is `neuralSearch`.
public struct SearchSemanticSearch: Codable, JSONEncodable {
    /// Indices from which to collect click and conversion events.  If null, the current index and all its replicas are
    /// used.
    public var eventSources: [String]?

    public init(eventSources: [String]? = nil) {
        self.eventSources = eventSources
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventSources
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.eventSources, forKey: .eventSources)
    }
}

extension SearchSemanticSearch: Equatable {
    public static func ==(lhs: SearchSemanticSearch, rhs: SearchSemanticSearch) -> Bool {
        lhs.eventSources == rhs.eventSources
    }
}

extension SearchSemanticSearch: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.eventSources?.hashValue)
    }
}
