// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct UserHighlightResult: Codable, JSONEncodable {
    public var userID: SearchHighlightResult
    public var clusterName: SearchHighlightResult

    public init(userID: SearchHighlightResult, clusterName: SearchHighlightResult) {
        self.userID = userID
        self.clusterName = clusterName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userID
        case clusterName
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.userID, forKey: .userID)
        try container.encode(self.clusterName, forKey: .clusterName)
    }
}

extension UserHighlightResult: Equatable {
    public static func ==(lhs: UserHighlightResult, rhs: UserHighlightResult) -> Bool {
        lhs.userID == rhs.userID &&
            lhs.clusterName == rhs.clusterName
    }
}

extension UserHighlightResult: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.userID.hashValue)
        hasher.combine(self.clusterName.hashValue)
    }
}
