// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct AgentWithVersionResponse: Codable, JSONEncodable {
    public var id: String
    public var name: String
    public var description: String?
    public var status: AgentStatus
    public var providerId: String?
    public var model: String?
    public var instructions: String
    public var systemPrompt: String?
    public var config: [String: AnyCodable]
    public var tools: [ToolConfigInput]?
    public var templateType: String?
    public var createdAt: String
    public var updatedAt: String?
    public var lastUsedAt: String?

    public init(
        id: String,
        name: String,
        description: String?,
        status: AgentStatus,
        providerId: String?,
        model: String? = nil,
        instructions: String,
        systemPrompt: String? = nil,
        config: [String: AnyCodable],
        tools: [ToolConfigInput]? = nil,
        templateType: String? = nil,
        createdAt: String,
        updatedAt: String?,
        lastUsedAt: String?
    ) {
        self.id = id
        self.name = name
        self.description = description
        self.status = status
        self.providerId = providerId
        self.model = model
        self.instructions = instructions
        self.systemPrompt = systemPrompt
        self.config = config
        self.tools = tools
        self.templateType = templateType
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastUsedAt = lastUsedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case description
        case status
        case providerId
        case model
        case instructions
        case systemPrompt
        case config
        case tools
        case templateType
        case createdAt
        case updatedAt
        case lastUsedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.description, forKey: .description)
        try container.encode(self.status, forKey: .status)
        try container.encode(self.providerId, forKey: .providerId)
        try container.encodeIfPresent(self.model, forKey: .model)
        try container.encode(self.instructions, forKey: .instructions)
        try container.encodeIfPresent(self.systemPrompt, forKey: .systemPrompt)
        try container.encode(self.config, forKey: .config)
        try container.encodeIfPresent(self.tools, forKey: .tools)
        try container.encodeIfPresent(self.templateType, forKey: .templateType)
        try container.encode(self.createdAt, forKey: .createdAt)
        try container.encode(self.updatedAt, forKey: .updatedAt)
        try container.encode(self.lastUsedAt, forKey: .lastUsedAt)
    }
}

extension AgentWithVersionResponse: Equatable {}

extension AgentWithVersionResponse: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id.hashValue)
        hasher.combine(self.name.hashValue)
        hasher.combine(self.description.hashValue)
        hasher.combine(self.status.hashValue)
        hasher.combine(self.providerId.hashValue)
        hasher.combine(self.model?.hashValue)
        hasher.combine(self.instructions.hashValue)
        hasher.combine(self.systemPrompt?.hashValue)
        hasher.combine(self.config.hashValue)
        hasher.combine(self.tools?.hashValue)
        hasher.combine(self.templateType?.hashValue)
        hasher.combine(self.createdAt.hashValue)
        hasher.combine(self.updatedAt.hashValue)
        hasher.combine(self.lastUsedAt.hashValue)
    }
}
