// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct AgentConfigUpdate: Codable, JSONEncodable {
    public var name: String?
    public var description: String?
    public var providerId: String?
    public var model: String?
    /// The agent prompt: defines the agent's role, tone, and goals. Guides how it answers using the provided context.
    /// Corresponds to the 'Agent prompt' field in the dashboard.
    public var instructions: String?
    /// The system prompt: defines system-level rules and constraints. Guides how the agent uses tools, features, and
    /// generates context. Prepended before `instructions` in the final prompt sent to the LLM. Typically injected by an
    /// agent template — modify with caution, as changes may affect behavior, tool usage, or response accuracy.
    /// Corresponds to the 'System prompt' field in the dashboard.
    public var systemPrompt: String?
    public var config: [String: AnyCodable]?
    public var tools: [ToolConfigInput]?
    public var templateType: String?

    public init(
        name: String? = nil,
        description: String? = nil,
        providerId: String? = nil,
        model: String? = nil,
        instructions: String? = nil,
        systemPrompt: String? = nil,
        config: [String: AnyCodable]? = nil,
        tools: [ToolConfigInput]? = nil,
        templateType: String? = nil
    ) {
        self.name = name
        self.description = description
        self.providerId = providerId
        self.model = model
        self.instructions = instructions
        self.systemPrompt = systemPrompt
        self.config = config
        self.tools = tools
        self.templateType = templateType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case providerId
        case model
        case instructions
        case systemPrompt
        case config
        case tools
        case templateType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.name, forKey: .name)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encodeIfPresent(self.providerId, forKey: .providerId)
        try container.encodeIfPresent(self.model, forKey: .model)
        try container.encodeIfPresent(self.instructions, forKey: .instructions)
        try container.encodeIfPresent(self.systemPrompt, forKey: .systemPrompt)
        try container.encodeIfPresent(self.config, forKey: .config)
        try container.encodeIfPresent(self.tools, forKey: .tools)
        try container.encodeIfPresent(self.templateType, forKey: .templateType)
    }
}

extension AgentConfigUpdate: Equatable {}

extension AgentConfigUpdate: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name?.hashValue)
        hasher.combine(self.description?.hashValue)
        hasher.combine(self.providerId?.hashValue)
        hasher.combine(self.model?.hashValue)
        hasher.combine(self.instructions?.hashValue)
        hasher.combine(self.systemPrompt?.hashValue)
        hasher.combine(self.config?.hashValue)
        hasher.combine(self.tools?.hashValue)
        hasher.combine(self.templateType?.hashValue)
    }
}
