// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public enum AgentCompletionRequestUnion: Codable, JSONEncodable, AbstractEncodable {
    case aguiCompletionRequest(AguiCompletionRequest)
    case agentCompletionRequest(AgentCompletionRequest)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .aguiCompletionRequest(value):
            try container.encode(value)
        case let .agentCompletionRequest(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AguiCompletionRequest.self) {
            self = .aguiCompletionRequest(value)
        } else if let value = try? container.decode(AgentCompletionRequest.self) {
            self = .agentCompletionRequest(value)
        } else {
            throw DecodingError.typeMismatch(
                Self.Type.self,
                .init(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unable to decode instance of AgentCompletionRequestUnion"
                )
            )
        }
    }

    public func GetActualInstance() -> Encodable {
        switch self {
        case let .aguiCompletionRequest(value):
            value as AguiCompletionRequest
        case let .agentCompletionRequest(value):
            value as AgentCompletionRequest
        }
    }
}

extension AgentCompletionRequestUnion: Equatable {}
extension AgentCompletionRequestUnion: Hashable {}
