// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct AlgoliaSearchToolConfig: Codable, JSONEncodable {
    public var name: String
    public var type: String
    public var indices: [AlgoliaSearchToolIndexConfig]

    public init(name: String, type: String, indices: [AlgoliaSearchToolIndexConfig]) {
        self.name = name
        self.type = type
        self.indices = indices
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case indices
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.type, forKey: .type)
        try container.encode(self.indices, forKey: .indices)
    }
}

extension AlgoliaSearchToolConfig: Equatable {}

extension AlgoliaSearchToolConfig: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name.hashValue)
        hasher.combine(self.type.hashValue)
        hasher.combine(self.indices.hashValue)
    }
}
