// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Configuration for the Algolia Recommend tool. Allows specifying recommend models and related parameters.
public struct AlgoliaRecommendToolConfigInput: Codable, JSONEncodable {
    public var name: String
    public var type: String
    public var allowedConfigs: [AlgoliaRecommendToolIndexConfig]?
    public var predefinedRecommendParameters: [String: AnyCodable]?

    public init(
        name: String,
        type: String,
        allowedConfigs: [AlgoliaRecommendToolIndexConfig]? = nil,
        predefinedRecommendParameters: [String: AnyCodable]? = nil
    ) {
        self.name = name
        self.type = type
        self.allowedConfigs = allowedConfigs
        self.predefinedRecommendParameters = predefinedRecommendParameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case type
        case allowedConfigs
        case predefinedRecommendParameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.type, forKey: .type)
        try container.encodeIfPresent(self.allowedConfigs, forKey: .allowedConfigs)
        try container.encodeIfPresent(self.predefinedRecommendParameters, forKey: .predefinedRecommendParameters)
    }
}

extension AlgoliaRecommendToolConfigInput: Equatable {}

extension AlgoliaRecommendToolConfigInput: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name.hashValue)
        hasher.combine(self.type.hashValue)
        hasher.combine(self.allowedConfigs?.hashValue)
        hasher.combine(self.predefinedRecommendParameters?.hashValue)
    }
}
