// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct AssistantMessageV4: Codable, JSONEncodable {
    public var id: String?
    public var role: String
    public var content: String
    public var parts: [AssistantPartV4]?
    public var toolInvocations: [ToolInvocationV4]?

    public init(
        id: String? = nil,
        role: String,
        content: String,
        parts: [AssistantPartV4]? = nil,
        toolInvocations: [ToolInvocationV4]? = nil
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.parts = parts
        self.toolInvocations = toolInvocations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case role
        case content
        case parts
        case toolInvocations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.id, forKey: .id)
        try container.encode(self.role, forKey: .role)
        try container.encode(self.content, forKey: .content)
        try container.encodeIfPresent(self.parts, forKey: .parts)
        try container.encodeIfPresent(self.toolInvocations, forKey: .toolInvocations)
    }
}

extension AssistantMessageV4: Equatable {}

extension AssistantMessageV4: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.id?.hashValue)
        hasher.combine(self.role.hashValue)
        hasher.combine(self.content.hashValue)
        hasher.combine(self.parts?.hashValue)
        hasher.combine(self.toolInvocations?.hashValue)
    }
}
