// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Azure OpenAI-specific provider input.
public struct AzureOpenAIProviderInput: Codable, JSONEncodable {
    public var apiKey: String
    public var azureEndpoint: String
    /// Azure model deployment name is required.
    public var azureDeployment: String
    public var apiVersion: String?

    public init(apiKey: String, azureEndpoint: String, azureDeployment: String, apiVersion: String? = nil) {
        self.apiKey = apiKey
        self.azureEndpoint = azureEndpoint
        self.azureDeployment = azureDeployment
        self.apiVersion = apiVersion
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiKey
        case azureEndpoint
        case azureDeployment
        case apiVersion
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.apiKey, forKey: .apiKey)
        try container.encode(self.azureEndpoint, forKey: .azureEndpoint)
        try container.encode(self.azureDeployment, forKey: .azureDeployment)
        try container.encodeIfPresent(self.apiVersion, forKey: .apiVersion)
    }
}

extension AzureOpenAIProviderInput: Equatable {}

extension AzureOpenAIProviderInput: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.apiKey.hashValue)
        hasher.combine(self.azureEndpoint.hashValue)
        hasher.combine(self.azureDeployment.hashValue)
        hasher.combine(self.apiVersion?.hashValue)
    }
}
