// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Compaction-specific telemetry, returned only by ``/context/compact``.  ``compacted`` makes the short-conversation
/// passthrough detectable: without it a caller cannot tell a no-op from a summary that happened to be short.
public struct CompactionStats: Codable, JSONEncodable {
    /// Whether a summary was actually produced. `false` means the payload passed through untouched (nothing older than
    /// the kept tail, or no summarizable text).
    public var compacted: Bool
    /// Number of transcript chunks summarized in the map phase. 0 on passthrough, 1 when the transcript fit in a single
    /// summarizer call.
    public var chunksProcessed: Int?
    /// Number of summarizer rounds. 1 for a direct summary; 2+ when chunk summaries had to be merged (map-reduce).
    public var passes: Int?
    /// Provider-reported input tokens summed across every summarizer call. Null when the provider reported no usage
    /// metadata.
    public var summarizerPromptTokens: Int?
    /// Provider-reported output tokens summed across every summarizer call. Null when the provider reported no usage
    /// metadata.
    public var summarizerCompletionTokens: Int?
    /// The requested output budget, echoed back when `targetTokensEstimate` was set.
    public var targetTokensEstimate: Int?

    public init(
        compacted: Bool,
        chunksProcessed: Int? = nil,
        passes: Int? = nil,
        summarizerPromptTokens: Int? = nil,
        summarizerCompletionTokens: Int? = nil,
        targetTokensEstimate: Int? = nil
    ) {
        self.compacted = compacted
        self.chunksProcessed = chunksProcessed
        self.passes = passes
        self.summarizerPromptTokens = summarizerPromptTokens
        self.summarizerCompletionTokens = summarizerCompletionTokens
        self.targetTokensEstimate = targetTokensEstimate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case compacted
        case chunksProcessed
        case passes
        case summarizerPromptTokens
        case summarizerCompletionTokens
        case targetTokensEstimate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.compacted, forKey: .compacted)
        try container.encodeIfPresent(self.chunksProcessed, forKey: .chunksProcessed)
        try container.encodeIfPresent(self.passes, forKey: .passes)
        try container.encodeIfPresent(self.summarizerPromptTokens, forKey: .summarizerPromptTokens)
        try container.encodeIfPresent(self.summarizerCompletionTokens, forKey: .summarizerCompletionTokens)
        try container.encodeIfPresent(self.targetTokensEstimate, forKey: .targetTokensEstimate)
    }
}

extension CompactionStats: Equatable {}

extension CompactionStats: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.compacted.hashValue)
        hasher.combine(self.chunksProcessed?.hashValue)
        hasher.combine(self.passes?.hashValue)
        hasher.combine(self.summarizerPromptTokens?.hashValue)
        hasher.combine(self.summarizerCompletionTokens?.hashValue)
        hasher.combine(self.targetTokensEstimate?.hashValue)
    }
}
