// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// A ``data-guardrail-violation`` part that an AI SDK v5 client sends back.  Send this part to tell the completions
/// endpoint that a guardrail blocked the previous turn.
public struct DataGuardrailViolationPartV5: Codable, JSONEncodable {
    public var type: String?
    public var data: GuardrailViolationDataV5

    public init(type: String? = nil, data: GuardrailViolationDataV5) {
        self.type = type
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.type, forKey: .type)
        try container.encode(self.data, forKey: .data)
    }
}

extension DataGuardrailViolationPartV5: Equatable {}

extension DataGuardrailViolationPartV5: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.type?.hashValue)
        hasher.combine(self.data.hashValue)
    }
}
