// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Minimal record of a guardrail decision, persisted on a blocked assistant message.  Present only when a guardrail
/// blocks a turn (the persisted parts are then just the fallback text); ``null`` on ordinary messages. Lets a blocked
/// turn be told apart from a short reply using conversation data alone.
public struct GuardrailOutcome: Codable, JSONEncodable {
    public var blocked: Bool
    public var category: String
    public var guardrailType: OneOfEnum?

    public init(blocked: Bool, category: String, guardrailType: OneOfEnum? = nil) {
        self.blocked = blocked
        self.category = category
        self.guardrailType = guardrailType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blocked
        case category
        case guardrailType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.blocked, forKey: .blocked)
        try container.encode(self.category, forKey: .category)
        try container.encodeIfPresent(self.guardrailType, forKey: .guardrailType)
    }
}

extension GuardrailOutcome: Equatable {}

extension GuardrailOutcome: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.blocked.hashValue)
        hasher.combine(self.category.hashValue)
        hasher.combine(self.guardrailType?.hashValue)
    }
}
