// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Views, clicks, and conversions attributed to the conversation.  Returned only when ``includeImpactAnalytics=true``.
/// ``null`` means the API could not supply the data -- NOT that there are zero outcomes -- and the response sets
/// ``analyticsDegraded`` to ``true``. Render that case as a data-load error rather than as zero-value badges.
public struct ImpactAnalytics: Codable, JSONEncodable {
    public var hasView: Bool
    public var hasClick: Bool
    public var hasConversion: Bool
    public var hasAlgoliaSearch: Bool

    public init(hasView: Bool, hasClick: Bool, hasConversion: Bool, hasAlgoliaSearch: Bool) {
        self.hasView = hasView
        self.hasClick = hasClick
        self.hasConversion = hasConversion
        self.hasAlgoliaSearch = hasAlgoliaSearch
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasView
        case hasClick
        case hasConversion
        case hasAlgoliaSearch
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.hasView, forKey: .hasView)
        try container.encode(self.hasClick, forKey: .hasClick)
        try container.encode(self.hasConversion, forKey: .hasConversion)
        try container.encode(self.hasAlgoliaSearch, forKey: .hasAlgoliaSearch)
    }
}

extension ImpactAnalytics: Equatable {}

extension ImpactAnalytics: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.hasView.hashValue)
        hasher.combine(self.hasClick.hashValue)
        hasher.combine(self.hasConversion.hashValue)
        hasher.combine(self.hasAlgoliaSearch.hashValue)
    }
}
