// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct ProviderAuthenticationCreate: Codable, JSONEncodable {
    public var name: String
    public var providerName: ProviderName
    public var input: ProviderInput

    public init(name: String, providerName: ProviderName, input: ProviderInput) {
        self.name = name
        self.providerName = providerName
        self.input = input
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case providerName
        case input
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        try container.encode(self.providerName, forKey: .providerName)
        try container.encode(self.input, forKey: .input)
    }
}

extension ProviderAuthenticationCreate: Equatable {}

extension ProviderAuthenticationCreate: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.name.hashValue)
        hasher.combine(self.providerName.hashValue)
        hasher.combine(self.input.hashValue)
    }
}
