// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct TextPart: Codable, JSONEncodable {
    public var type: String
    public var text: String

    public init(type: String, text: String) {
        self.type = type
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.type, forKey: .type)
        try container.encode(self.text, forKey: .text)
    }
}

extension TextPart: Equatable {}

extension TextPart: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.type.hashValue)
        hasher.combine(self.text.hashValue)
    }
}
