// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public enum TypoToleranceUnion: Codable, JSONEncodable, AbstractEncodable {
    case agentStudioTypoToleranceEnum(AgentStudioTypoToleranceEnum)
    case bool(Bool)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .agentStudioTypoToleranceEnum(value):
            try container.encode(value)
        case let .bool(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AgentStudioTypoToleranceEnum.self) {
            self = .agentStudioTypoToleranceEnum(value)
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else {
            throw DecodingError.typeMismatch(
                Self.Type.self,
                .init(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unable to decode instance of TypoToleranceUnion"
                )
            )
        }
    }

    public func GetActualInstance() -> Encodable {
        switch self {
        case let .agentStudioTypoToleranceEnum(value):
            value as AgentStudioTypoToleranceEnum
        case let .bool(value):
            value as Bool
        }
    }
}

extension TypoToleranceUnion: Equatable {}
extension TypoToleranceUnion: Hashable {}
