// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

open class AgentStudioClient {
    public private(set) var configuration: AgentStudioClientConfiguration
    private var transporter: Transporter

    var appID: String {
        self.configuration.appID
    }

    public init(configuration: AgentStudioClientConfiguration, transporter: Transporter) {
        self.configuration = configuration
        self.transporter = transporter
    }

    public convenience init(configuration: AgentStudioClientConfiguration) {
        self.init(configuration: configuration, transporter: Transporter(configuration: configuration))
    }

    public convenience init(appID: String, apiKey: String) throws {
        try self.init(configuration: AgentStudioClientConfiguration(appID: appID, apiKey: apiKey))
    }

    open func setClientApiKey(apiKey: String) {
        self.configuration.apiKey = apiKey
        self.transporter.setClientApiKey(apiKey: apiKey)
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter allowedDomainBulkInsert: (body)
    /// - returns: AllowedDomainListResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func bulkCreateAllowedDomains(
        agentId: String,
        allowedDomainBulkInsert: AllowedDomainBulkInsert,
        requestOptions: RequestOptions? = nil
    ) async throws -> AllowedDomainListResponse {
        let response: Response<AllowedDomainListResponse> = try await bulkCreateAllowedDomainsWithHTTPInfo(
            agentId: agentId,
            allowedDomainBulkInsert: allowedDomainBulkInsert,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Add multiple allowed domain patterns. Duplicates are skipped.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter allowedDomainBulkInsert: (body)
    // - returns: RequestBuilder<AllowedDomainListResponse>

    open func bulkCreateAllowedDomainsWithHTTPInfo(
        agentId: String,
        allowedDomainBulkInsert: AllowedDomainBulkInsert,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AllowedDomainListResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "bulkCreateAllowedDomains")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains/bulk"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = allowedDomainBulkInsert
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter allowedDomainBulkDelete: (body)
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func bulkDeleteAllowedDomains(
        agentId: String,
        allowedDomainBulkDelete: AllowedDomainBulkDelete,
        requestOptions: RequestOptions? = nil
    ) async throws {
        try await self.bulkDeleteAllowedDomainsWithHTTPInfo(
            agentId: agentId,
            allowedDomainBulkDelete: allowedDomainBulkDelete,
            requestOptions: requestOptions
        )
    }

    /// Delete allowed domains by id list.
    /// Required API Key ACLs:
    ///  - editSettings
    ///
    /// - parameter agentId: (path) The agentId.
    ///
    /// - parameter allowedDomainBulkDelete: (body)
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func bulkDeleteAllowedDomainsWithHTTPInfo(
        agentId: String,
        allowedDomainBulkDelete: AllowedDomainBulkDelete,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "bulkDeleteAllowedDomains")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains/bulk"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = allowedDomainBulkDelete
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentConfigCreate: (body)
    /// - returns: AgentWithVersionResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createAgent(
        agentConfigCreate: AgentConfigCreate,
        requestOptions: RequestOptions? = nil
    ) async throws -> AgentWithVersionResponse {
        let response: Response<AgentWithVersionResponse> = try await createAgentWithHTTPInfo(
            agentConfigCreate: agentConfigCreate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Create a new agent.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentConfigCreate: (body)
    // - returns: RequestBuilder<AgentWithVersionResponse>

    open func createAgentWithHTTPInfo(
        agentConfigCreate: AgentConfigCreate,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AgentWithVersionResponse> {
        let resourcePath = "/agent-studio/1/agents"
        let body = agentConfigCreate
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter allowedDomainCreate: (body)
    /// - returns: AllowedDomainResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createAgentAllowedDomain(
        agentId: String,
        allowedDomainCreate: AllowedDomainCreate,
        requestOptions: RequestOptions? = nil
    ) async throws -> AllowedDomainResponse {
        let response: Response<AllowedDomainResponse> = try await createAgentAllowedDomainWithHTTPInfo(
            agentId: agentId,
            allowedDomainCreate: allowedDomainCreate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Add a single allowed domain pattern (e.g. https://app.example.com or *.example.com).
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter allowedDomainCreate: (body)
    // - returns: RequestBuilder<AllowedDomainResponse>

    open func createAgentAllowedDomainWithHTTPInfo(
        agentId: String,
        allowedDomainCreate: AllowedDomainCreate,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AllowedDomainResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "createAgentAllowedDomain")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = allowedDomainCreate
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter compatibilityMode: (query) Compatibility mode for the completion API.
    /// - parameter agentCompletionRequest: (body)
    /// - parameter stream: (query) Whether to stream the response or not. (optional, default to true)
    /// - parameter cache: (query) Use cached responses if available. (optional, default to true)
    /// - parameter memory: (query) Set to false to disable memory (enabled by default). (optional)
    /// - parameter analytics: (query) Set to false to skip analytics for this completion (default: true). Disables
    /// Agent Studio BigQuery analytics, Algolia search analytics, click analytics, and query-suggestions training.
    /// Useful for offline-eval workflows. (optional, default to true)
    /// - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    /// - returns: [String: AnyCodable]
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createAgentCompletion(
        agentId: String,
        compatibilityMode: CompatibilityMode,
        agentCompletionRequest: AgentCompletionRequest,
        stream: Bool? = nil,
        cache: Bool? = nil,
        memory: Bool? = nil,
        analytics: Bool? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> [String: AnyCodable] {
        let response: Response<[String: AnyCodable]> = try await createAgentCompletionWithHTTPInfo(
            agentId: agentId,
            compatibilityMode: compatibilityMode,
            agentCompletionRequest: agentCompletionRequest,
            stream: stream,
            cache: cache,
            memory: memory,
            analytics: analytics,
            xAlgoliaSecureUserToken: xAlgoliaSecureUserToken,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Create a completion for the specified agent.  This endpoint handles two types of requests: 1. Normal completion
    // request: User message -> Agent response 2. Tool approval response: User approval -> Execute tool -> Agent response  Tool Approval Flow (for MCP tools with requiresApproval: true): - Request 1: User sends message -> Agent requests tool call -> Return approval request - Request 2: User approves -> Execute tool -> Agent continues with result.
    // Required API Key ACLs:
    //  - search
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter compatibilityMode: (query) Compatibility mode for the completion API.
    //
    // - parameter agentCompletionRequest: (body)
    //
    // - parameter stream: (query) Whether to stream the response or not. (optional, default to true)
    //
    // - parameter cache: (query) Use cached responses if available. (optional, default to true)
    //
    // - parameter memory: (query) Set to false to disable memory (enabled by default). (optional)
    //
    // - parameter analytics: (query) Set to false to skip analytics for this completion (default: true). Disables Agent
    // Studio BigQuery analytics, Algolia search analytics, click analytics, and query-suggestions training. Useful for
    // offline-eval workflows. (optional, default to true)
    //
    // - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    // - returns: RequestBuilder<[String: AnyCodable]>

    open func createAgentCompletionWithHTTPInfo(
        agentId: String,
        compatibilityMode: CompatibilityMode,
        agentCompletionRequest: AgentCompletionRequest,
        stream: Bool? = nil,
        cache: Bool? = nil,
        memory: Bool? = nil,
        analytics: Bool? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<[String: AnyCodable]> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "createAgentCompletion")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/completions"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = agentCompletionRequest
        let queryParameters: [String: Any?] = [
            "compatibilityMode": compatibilityMode.encodeToJSON(),
            "stream": stream?.encodeToJSON(),
            "cache": cache?.encodeToJSON(),
            "memory": memory?.encodeToJSON(),
            "analytics": analytics?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = [
            "X-Algolia-Secure-User-Token": xAlgoliaSecureUserToken?.encodeToJSON(),
        ]

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter feedbackCreationRequest: (body)
    /// - returns: FeedbackResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createFeedback(
        feedbackCreationRequest: FeedbackCreationRequest,
        requestOptions: RequestOptions? = nil
    ) async throws -> FeedbackResponse {
        let response: Response<FeedbackResponse> = try await createFeedbackWithHTTPInfo(
            feedbackCreationRequest: feedbackCreationRequest,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Create new feedback entry.
    // Required API Key ACLs:
    //  - search
    //
    // - parameter feedbackCreationRequest: (body)
    // - returns: RequestBuilder<FeedbackResponse>

    open func createFeedbackWithHTTPInfo(
        feedbackCreationRequest: FeedbackCreationRequest,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<FeedbackResponse> {
        let resourcePath = "/agent-studio/1/feedback"
        let body = feedbackCreationRequest
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter providerAuthenticationCreate: (body)
    /// - returns: ProviderAuthenticationResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createProvider(
        providerAuthenticationCreate: ProviderAuthenticationCreate,
        requestOptions: RequestOptions? = nil
    ) async throws -> ProviderAuthenticationResponse {
        let response: Response<ProviderAuthenticationResponse> = try await createProviderWithHTTPInfo(
            providerAuthenticationCreate: providerAuthenticationCreate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Create Provider.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter providerAuthenticationCreate: (body)
    // - returns: RequestBuilder<ProviderAuthenticationResponse>

    open func createProviderWithHTTPInfo(
        providerAuthenticationCreate: ProviderAuthenticationCreate,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<ProviderAuthenticationResponse> {
        let resourcePath = "/agent-studio/1/providers"
        let body = providerAuthenticationCreate
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter secretKeyCreate: (body)
    /// - returns: SecretKeyResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func createSecretKey(
        secretKeyCreate: SecretKeyCreate,
        requestOptions: RequestOptions? = nil
    ) async throws -> SecretKeyResponse {
        let response: Response<SecretKeyResponse> = try await createSecretKeyWithHTTPInfo(
            secretKeyCreate: secretKeyCreate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Create Secret Key.
    // Required API Key ACLs:
    //  - admin
    //
    // - parameter secretKeyCreate: (body)
    // - returns: RequestBuilder<SecretKeyResponse>

    open func createSecretKeyWithHTTPInfo(
        secretKeyCreate: SecretKeyCreate,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<SecretKeyResponse> {
        let resourcePath = "/agent-studio/1/secret-keys"
        let body = secretKeyCreate
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    /// - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    /// - returns: AnyCodable
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func customDelete(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AnyCodable {
        let response: Response<AnyCodable> = try await customDeleteWithHTTPInfo(
            path: path,
            parameters: parameters,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // This method lets you send requests to the Algolia REST API.
    //
    //
    // - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    //
    // - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    // - returns: RequestBuilder<AnyCodable>

    open func customDeleteWithHTTPInfo(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !path.isEmpty else {
            throw AlgoliaError.invalidArgument("path", "customDelete")
        }

        var resourcePath = "/agent-studio/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        resourcePath = resourcePath.replacingOccurrences(
            of: "{path}",
            with: pathPreEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: AnyCodable]? = parameters

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    /// - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    /// - returns: AnyCodable
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func customGet(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AnyCodable {
        let response: Response<AnyCodable> = try await customGetWithHTTPInfo(
            path: path,
            parameters: parameters,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // This method lets you send requests to the Algolia REST API.
    //
    //
    // - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    //
    // - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    // - returns: RequestBuilder<AnyCodable>

    open func customGetWithHTTPInfo(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !path.isEmpty else {
            throw AlgoliaError.invalidArgument("path", "customGet")
        }

        var resourcePath = "/agent-studio/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        resourcePath = resourcePath.replacingOccurrences(
            of: "{path}",
            with: pathPreEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: AnyCodable]? = parameters

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    /// - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    /// - parameter body: (body) Parameters to send with the custom request. (optional)
    /// - returns: AnyCodable
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func customPost(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        body: Codable? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AnyCodable {
        let response: Response<AnyCodable> = try await customPostWithHTTPInfo(
            path: path,
            parameters: parameters,
            body: body,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // This method lets you send requests to the Algolia REST API.
    //
    //
    // - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    //
    // - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    //
    // - parameter body: (body) Parameters to send with the custom request. (optional)
    // - returns: RequestBuilder<AnyCodable>

    open func customPostWithHTTPInfo(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        body: Codable? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !path.isEmpty else {
            throw AlgoliaError.invalidArgument("path", "customPost")
        }

        var resourcePath = "/agent-studio/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        resourcePath = resourcePath.replacingOccurrences(
            of: "{path}",
            with: pathPreEscape,
            options: .literal,
            range: nil
        )
        let body = body
        let queryParameters: [String: AnyCodable]? = parameters

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body ?? AnyCodable(),
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    /// - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    /// - parameter body: (body) Parameters to send with the custom request. (optional)
    /// - returns: AnyCodable
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func customPut(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        body: Codable? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> AnyCodable {
        let response: Response<AnyCodable> = try await customPutWithHTTPInfo(
            path: path,
            parameters: parameters,
            body: body,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // This method lets you send requests to the Algolia REST API.
    //
    //
    // - parameter path: (path) Path of the endpoint, for example `1/newFeature`.
    //
    // - parameter parameters: (query) Query parameters to apply to the current query. (optional)
    //
    // - parameter body: (body) Parameters to send with the custom request. (optional)
    // - returns: RequestBuilder<AnyCodable>

    open func customPutWithHTTPInfo(
        path: String,
        parameters: [String: AnyCodable]? = nil,
        body: Codable? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !path.isEmpty else {
            throw AlgoliaError.invalidArgument("path", "customPut")
        }

        var resourcePath = "/agent-studio/{path}"
        let pathPreEscape = "\(APIHelper.mapValueToPathItem(path))"
        resourcePath = resourcePath.replacingOccurrences(
            of: "{path}",
            with: pathPreEscape,
            options: .literal,
            range: nil
        )
        let body = body
        let queryParameters: [String: AnyCodable]? = parameters

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "PUT",
            path: resourcePath,
            data: body ?? AnyCodable(),
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteAgent(agentId: String, requestOptions: RequestOptions? = nil) async throws {
        try await self.deleteAgentWithHTTPInfo(agentId: agentId, requestOptions: requestOptions)
    }

    /// Delete the specified agent.
    /// Required API Key ACLs:
    ///  - editSettings
    ///
    /// - parameter agentId: (path) The agentId.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteAgentWithHTTPInfo(
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "deleteAgent")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    /// - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteAgentConversations(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws {
        try await self.deleteAgentConversationsWithHTTPInfo(
            agentId: agentId,
            startDate: startDate,
            endDate: endDate,
            requestOptions: requestOptions
        )
    }

    /// Deletes the conversations matching the given filers.
    /// Required API Key ACLs:
    ///  - logs
    ///
    /// - parameter agentId: (path) The agentId.
    ///
    /// - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    ///
    /// - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteAgentConversationsWithHTTPInfo(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "deleteAgentConversations")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/conversations"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "startDate": startDate?.encodeToJSON(),
            "endDate": endDate?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter domainId: (path) The domainId.
    /// - parameter agentId: (path) The agentId.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteAllowedDomain(
        domainId: String,
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        try await self.deleteAllowedDomainWithHTTPInfo(
            domainId: domainId,
            agentId: agentId,
            requestOptions: requestOptions
        )
    }

    /// Remove an allowed domain by id.
    /// Required API Key ACLs:
    ///  - editSettings
    ///
    /// - parameter domainId: (path) The domainId.
    ///
    /// - parameter agentId: (path) The agentId.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteAllowedDomainWithHTTPInfo(
        domainId: String,
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !domainId.isEmpty else {
            throw AlgoliaError.invalidArgument("domainId", "deleteAllowedDomain")
        }

        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "deleteAllowedDomain")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains/{domainId}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{domainId}",
            with: domainIdPostEscape,
            options: .literal,
            range: nil
        )
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter conversationId: (path) The conversationId.
    /// - parameter agentId: (path) The agentId.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteConversation(
        conversationId: String,
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws {
        try await self.deleteConversationWithHTTPInfo(
            conversationId: conversationId,
            agentId: agentId,
            requestOptions: requestOptions
        )
    }

    /// Deletes the conversation with the given ID.
    /// Required API Key ACLs:
    ///  - logs
    ///
    /// - parameter conversationId: (path) The conversationId.
    ///
    /// - parameter agentId: (path) The agentId.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteConversationWithHTTPInfo(
        conversationId: String,
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !conversationId.isEmpty else {
            throw AlgoliaError.invalidArgument("conversationId", "deleteConversation")
        }

        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "deleteConversation")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/conversations/{conversationId}"
        let conversationIdPreEscape = "\(APIHelper.mapValueToPathItem(conversationId))"
        let conversationIdPostEscape = conversationIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{conversationId}",
            with: conversationIdPostEscape,
            options: .literal,
            range: nil
        )
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter providerId: (path) The providerId.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteProvider(providerId: String, requestOptions: RequestOptions? = nil) async throws {
        try await self.deleteProviderWithHTTPInfo(providerId: providerId, requestOptions: requestOptions)
    }

    /// Delete Provider.
    /// Required API Key ACLs:
    ///  - editSettings
    ///
    /// - parameter providerId: (path) The providerId.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteProviderWithHTTPInfo(
        providerId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !providerId.isEmpty else {
            throw AlgoliaError.invalidArgument("providerId", "deleteProvider")
        }

        var resourcePath = "/agent-studio/1/providers/{providerId}"
        let providerIdPreEscape = "\(APIHelper.mapValueToPathItem(providerId))"
        let providerIdPostEscape = providerIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{providerId}",
            with: providerIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter secretKeyId: (path) The secretKeyId.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteSecretKey(secretKeyId: String, requestOptions: RequestOptions? = nil) async throws {
        try await self.deleteSecretKeyWithHTTPInfo(secretKeyId: secretKeyId, requestOptions: requestOptions)
    }

    /// Delete Secret Key.
    /// Required API Key ACLs:
    ///  - admin
    ///
    /// - parameter secretKeyId: (path) The secretKeyId.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteSecretKeyWithHTTPInfo(
        secretKeyId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !secretKeyId.isEmpty else {
            throw AlgoliaError.invalidArgument("secretKeyId", "deleteSecretKey")
        }

        var resourcePath = "/agent-studio/1/secret-keys/{secretKeyId}"
        let secretKeyIdPreEscape = "\(APIHelper.mapValueToPathItem(secretKeyId))"
        let secretKeyIdPostEscape = secretKeyIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{secretKeyId}",
            with: secretKeyIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter userToken: (path) The userToken.
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func deleteUserData(userToken: String, requestOptions: RequestOptions? = nil) async throws {
        try await self.deleteUserDataWithHTTPInfo(userToken: userToken, requestOptions: requestOptions)
    }

    /// Permanently deletes all messages for the given user token. Does not delete conversations.
    /// Required API Key ACLs:
    ///  - logs
    ///
    /// - parameter userToken: (path) The userToken.
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func deleteUserDataWithHTTPInfo(
        userToken: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !userToken.isEmpty else {
            throw AlgoliaError.invalidArgument("userToken", "deleteUserData")
        }

        var resourcePath = "/agent-studio/1/user-data/{userToken}"
        let userTokenPreEscape = "\(APIHelper.mapValueToPathItem(userToken))"
        let userTokenPostEscape = userTokenPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{userToken}",
            with: userTokenPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    /// - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    /// - returns: [ConversationFullResponse]
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func exportConversations(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> [ConversationFullResponse] {
        let response: Response<[ConversationFullResponse]> = try await exportConversationsWithHTTPInfo(
            agentId: agentId,
            startDate: startDate,
            endDate: endDate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Exports all conversations based on the passed filters.
    // Required API Key ACLs:
    //  - logs
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    //
    // - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    // - returns: RequestBuilder<[ConversationFullResponse]>

    open func exportConversationsWithHTTPInfo(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<[ConversationFullResponse]> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "exportConversations")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/conversations/export"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "startDate": startDate?.encodeToJSON(),
            "endDate": endDate?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - returns: AgentWithVersionResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getAgent(
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AgentWithVersionResponse {
        let response: Response<AgentWithVersionResponse> = try await getAgentWithHTTPInfo(
            agentId: agentId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Retrieve details of the specified agent.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter agentId: (path) The agentId.
    // - returns: RequestBuilder<AgentWithVersionResponse>

    open func getAgentWithHTTPInfo(
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AgentWithVersionResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "getAgent")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter domainId: (path) The domainId.
    /// - parameter agentId: (path) The agentId.
    /// - returns: AllowedDomainResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getAllowedDomain(
        domainId: String,
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AllowedDomainResponse {
        let response: Response<AllowedDomainResponse> = try await getAllowedDomainWithHTTPInfo(
            domainId: domainId,
            agentId: agentId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get a single allowed domain by id.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter domainId: (path) The domainId.
    //
    // - parameter agentId: (path) The agentId.
    // - returns: RequestBuilder<AllowedDomainResponse>

    open func getAllowedDomainWithHTTPInfo(
        domainId: String,
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AllowedDomainResponse> {
        guard !domainId.isEmpty else {
            throw AlgoliaError.invalidArgument("domainId", "getAllowedDomain")
        }

        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "getAllowedDomain")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains/{domainId}"
        let domainIdPreEscape = "\(APIHelper.mapValueToPathItem(domainId))"
        let domainIdPostEscape = domainIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{domainId}",
            with: domainIdPostEscape,
            options: .literal,
            range: nil
        )
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - returns: ApplicationConfigResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getConfiguration(requestOptions: RequestOptions? = nil) async throws -> ApplicationConfigResponse {
        let response: Response<ApplicationConfigResponse> =
            try await getConfigurationWithHTTPInfo(requestOptions: requestOptions)

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get Configuration.
    // Required API Key ACLs:
    //  - logs
    //     - returns: RequestBuilder<ApplicationConfigResponse>

    open func getConfigurationWithHTTPInfo(requestOptions userRequestOptions: RequestOptions? = nil) async throws
    -> Response<ApplicationConfigResponse> {
        let resourcePath = "/agent-studio/1/configuration"
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter conversationId: (path) The conversationId.
    /// - parameter agentId: (path) The agentId.
    /// - parameter includeFeedback: (query) Include feedback for the conversation. (optional, default to false)
    /// - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    /// - returns: ConversationFullResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getConversation(
        conversationId: String,
        agentId: String,
        includeFeedback: Bool? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> ConversationFullResponse {
        let response: Response<ConversationFullResponse> = try await getConversationWithHTTPInfo(
            conversationId: conversationId,
            agentId: agentId,
            includeFeedback: includeFeedback,
            xAlgoliaSecureUserToken: xAlgoliaSecureUserToken,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Retrieves the conversation and its messages for the given ID.
    // Required API Key ACLs:
    //  - logs
    //
    // - parameter conversationId: (path) The conversationId.
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter includeFeedback: (query) Include feedback for the conversation. (optional, default to false)
    //
    // - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    // - returns: RequestBuilder<ConversationFullResponse>

    open func getConversationWithHTTPInfo(
        conversationId: String,
        agentId: String,
        includeFeedback: Bool? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<ConversationFullResponse> {
        guard !conversationId.isEmpty else {
            throw AlgoliaError.invalidArgument("conversationId", "getConversation")
        }

        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "getConversation")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/conversations/{conversationId}"
        let conversationIdPreEscape = "\(APIHelper.mapValueToPathItem(conversationId))"
        let conversationIdPostEscape = conversationIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{conversationId}",
            with: conversationIdPostEscape,
            options: .literal,
            range: nil
        )
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "includeFeedback": includeFeedback?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = [
            "X-Algolia-Secure-User-Token": xAlgoliaSecureUserToken?.encodeToJSON(),
        ]

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter providerId: (path) The providerId.
    /// - returns: ProviderAuthenticationResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getProvider(
        providerId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> ProviderAuthenticationResponse {
        let response: Response<ProviderAuthenticationResponse> = try await getProviderWithHTTPInfo(
            providerId: providerId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get Provider.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter providerId: (path) The providerId.
    // - returns: RequestBuilder<ProviderAuthenticationResponse>

    open func getProviderWithHTTPInfo(
        providerId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<ProviderAuthenticationResponse> {
        guard !providerId.isEmpty else {
            throw AlgoliaError.invalidArgument("providerId", "getProvider")
        }

        var resourcePath = "/agent-studio/1/providers/{providerId}"
        let providerIdPreEscape = "\(APIHelper.mapValueToPathItem(providerId))"
        let providerIdPostEscape = providerIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{providerId}",
            with: providerIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter secretKeyId: (path) The secretKeyId.
    /// - returns: SecretKeyResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getSecretKey(
        secretKeyId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> SecretKeyResponse {
        let response: Response<SecretKeyResponse> = try await getSecretKeyWithHTTPInfo(
            secretKeyId: secretKeyId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get Secret Key.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter secretKeyId: (path) The secretKeyId.
    // - returns: RequestBuilder<SecretKeyResponse>

    open func getSecretKeyWithHTTPInfo(
        secretKeyId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<SecretKeyResponse> {
        guard !secretKeyId.isEmpty else {
            throw AlgoliaError.invalidArgument("secretKeyId", "getSecretKey")
        }

        var resourcePath = "/agent-studio/1/secret-keys/{secretKeyId}"
        let secretKeyIdPreEscape = "\(APIHelper.mapValueToPathItem(secretKeyId))"
        let secretKeyIdPostEscape = secretKeyIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{secretKeyId}",
            with: secretKeyIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter userToken: (path) The userToken.
    /// - returns: UserDataResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func getUserData(userToken: String, requestOptions: RequestOptions? = nil) async throws -> UserDataResponse {
        let response: Response<UserDataResponse> = try await getUserDataWithHTTPInfo(
            userToken: userToken,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Retrieves all memories, conversations and their messages for the given user token.
    // Required API Key ACLs:
    //  - logs
    //
    // - parameter userToken: (path) The userToken.
    // - returns: RequestBuilder<UserDataResponse>

    open func getUserDataWithHTTPInfo(
        userToken: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<UserDataResponse> {
        guard !userToken.isEmpty else {
            throw AlgoliaError.invalidArgument("userToken", "getUserData")
        }

        var resourcePath = "/agent-studio/1/user-data/{userToken}"
        let userTokenPreEscape = "\(APIHelper.mapValueToPathItem(userToken))"
        let userTokenPostEscape = userTokenPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{userToken}",
            with: userTokenPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter before: (query) Delete entries strictly before this date (exclusive, YYYY-MM-DD). (optional)
    /// - returns: Void
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func invalidateAgentCache(
        agentId: String,
        before: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws {
        try await self.invalidateAgentCacheWithHTTPInfo(
            agentId: agentId,
            before: before,
            requestOptions: requestOptions
        )
    }

    /// Invalidate cached completions for this agent. Filter with `before` (exclusive).
    /// Required API Key ACLs:
    ///  - editSettings
    ///
    /// - parameter agentId: (path) The agentId.
    ///
    /// - parameter before: (query) Delete entries strictly before this date (exclusive, YYYY-MM-DD). (optional)
    /// - returns: RequestBuilder<Void>
    @discardableResult
    open func invalidateAgentCacheWithHTTPInfo(
        agentId: String,
        before: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AnyCodable> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "invalidateAgentCache")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/cache"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "before": before?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "DELETE",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - returns: AllowedDomainListResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listAgentAllowedDomains(
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AllowedDomainListResponse {
        let response: Response<AllowedDomainListResponse> = try await listAgentAllowedDomainsWithHTTPInfo(
            agentId: agentId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // List all allowed domain patterns for this agent.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter agentId: (path) The agentId.
    // - returns: RequestBuilder<AllowedDomainListResponse>

    open func listAgentAllowedDomainsWithHTTPInfo(
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AllowedDomainListResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "listAgentAllowedDomains")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/allowed-domains"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    /// - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    /// - parameter includeFeedback: (query) Include feedback per conversation. (optional)
    /// - parameter feedbackVote: (query) Filter by feedback value (requires includeFeedback=true). (optional)
    /// - parameter page: (query) Page number. (optional, default to 1)
    /// - parameter limit: (query) Items per page. (optional, default to 20)
    /// - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    /// - returns: PaginatedConversationsResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listAgentConversations(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        includeFeedback: Bool? = nil,
        feedbackVote: Int? = nil,
        page: Int? = nil,
        limit: Int? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> PaginatedConversationsResponse {
        let response: Response<PaginatedConversationsResponse> = try await listAgentConversationsWithHTTPInfo(
            agentId: agentId,
            startDate: startDate,
            endDate: endDate,
            includeFeedback: includeFeedback,
            feedbackVote: feedbackVote,
            page: page,
            limit: limit,
            xAlgoliaSecureUserToken: xAlgoliaSecureUserToken,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Retrieves the conversations for the given agent ID.
    // Required API Key ACLs:
    //  - logs
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter startDate: (query) Filter conversations created after this date (format: YYYY-MM-DD). (optional)
    //
    // - parameter endDate: (query) Filter conversations created before this date (format: YYYY-MM-DD). (optional)
    //
    // - parameter includeFeedback: (query) Include feedback per conversation. (optional)
    //
    // - parameter feedbackVote: (query) Filter by feedback value (requires includeFeedback=true). (optional)
    //
    // - parameter page: (query) Page number. (optional, default to 1)
    //
    // - parameter limit: (query) Items per page. (optional, default to 20)
    //
    // - parameter xAlgoliaSecureUserToken: (header) The X-Algolia-Secure-User-Token. (optional)
    // - returns: RequestBuilder<PaginatedConversationsResponse>

    open func listAgentConversationsWithHTTPInfo(
        agentId: String,
        startDate: String? = nil,
        endDate: String? = nil,
        includeFeedback: Bool? = nil,
        feedbackVote: Int? = nil,
        page: Int? = nil,
        limit: Int? = nil,
        xAlgoliaSecureUserToken: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<PaginatedConversationsResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "listAgentConversations")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/conversations"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "startDate": startDate?.encodeToJSON(),
            "endDate": endDate?.encodeToJSON(),
            "includeFeedback": includeFeedback?.encodeToJSON(),
            "feedbackVote": feedbackVote?.encodeToJSON(),
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = [
            "X-Algolia-Secure-User-Token": xAlgoliaSecureUserToken?.encodeToJSON(),
        ]

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter page: (query) Page number. (optional, default to 1)
    /// - parameter limit: (query) Items per page. (optional, default to 10)
    /// - parameter providerId: (query) Filter by provider id. (optional)
    /// - returns: PaginatedAgentsResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listAgents(
        page: Int? = nil,
        limit: Int? = nil,
        providerId: String? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> PaginatedAgentsResponse {
        let response: Response<PaginatedAgentsResponse> = try await listAgentsWithHTTPInfo(
            page: page,
            limit: limit,
            providerId: providerId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // List all agents with pagination and filtering.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter page: (query) Page number. (optional, default to 1)
    //
    // - parameter limit: (query) Items per page. (optional, default to 10)
    //
    // - parameter providerId: (query) Filter by provider id. (optional)
    // - returns: RequestBuilder<PaginatedAgentsResponse>

    open func listAgentsWithHTTPInfo(
        page: Int? = nil,
        limit: Int? = nil,
        providerId: String? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<PaginatedAgentsResponse> {
        let resourcePath = "/agent-studio/1/agents"
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "providerId": providerId?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - returns: [String: [String]]
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listModels(requestOptions: RequestOptions? = nil) async throws -> [String: [String]] {
        let response: Response<[String: [String]]> = try await listModelsWithHTTPInfo(requestOptions: requestOptions)

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get Provider Models.
    // Required API Key ACLs:
    //  - settings
    //     - returns: RequestBuilder<[String: [String]]>

    open func listModelsWithHTTPInfo(requestOptions userRequestOptions: RequestOptions? = nil) async throws
    -> Response<[String: [String]]> {
        let resourcePath = "/agent-studio/1/providers/models"
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter providerId: (path) The providerId.
    /// - returns: [String]
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listProviderModels(providerId: String, requestOptions: RequestOptions? = nil) async throws -> [String] {
        let response: Response<[String]> = try await listProviderModelsWithHTTPInfo(
            providerId: providerId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Get available models for a specific provider.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter providerId: (path) The providerId.
    // - returns: RequestBuilder<[String]>

    open func listProviderModelsWithHTTPInfo(
        providerId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<[String]> {
        guard !providerId.isEmpty else {
            throw AlgoliaError.invalidArgument("providerId", "listProviderModels")
        }

        var resourcePath = "/agent-studio/1/providers/{providerId}/models"
        let providerIdPreEscape = "\(APIHelper.mapValueToPathItem(providerId))"
        let providerIdPostEscape = providerIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{providerId}",
            with: providerIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter page: (query) Page number. (optional, default to 1)
    /// - parameter limit: (query) Items per page. (optional, default to 10)
    /// - returns: PaginatedProviderAuthenticationsResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listProviders(
        page: Int? = nil,
        limit: Int? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> PaginatedProviderAuthenticationsResponse {
        let response: Response<PaginatedProviderAuthenticationsResponse> = try await listProvidersWithHTTPInfo(
            page: page,
            limit: limit,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // List Providers.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter page: (query) Page number. (optional, default to 1)
    //
    // - parameter limit: (query) Items per page. (optional, default to 10)
    // - returns: RequestBuilder<PaginatedProviderAuthenticationsResponse>

    open func listProvidersWithHTTPInfo(
        page: Int? = nil,
        limit: Int? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<PaginatedProviderAuthenticationsResponse> {
        let resourcePath = "/agent-studio/1/providers"
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter page: (query) Page number. (optional, default to 1)
    /// - parameter limit: (query) Items per page. (optional, default to 10)
    /// - returns: PaginatedSecretKeysResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func listSecretKeys(
        page: Int? = nil,
        limit: Int? = nil,
        requestOptions: RequestOptions? = nil
    ) async throws -> PaginatedSecretKeysResponse {
        let response: Response<PaginatedSecretKeysResponse> = try await listSecretKeysWithHTTPInfo(
            page: page,
            limit: limit,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // List Secret Keys.
    // Required API Key ACLs:
    //  - settings
    //
    // - parameter page: (query) Page number. (optional, default to 1)
    //
    // - parameter limit: (query) Items per page. (optional, default to 10)
    // - returns: RequestBuilder<PaginatedSecretKeysResponse>

    open func listSecretKeysWithHTTPInfo(
        page: Int? = nil,
        limit: Int? = nil,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<PaginatedSecretKeysResponse> {
        let resourcePath = "/agent-studio/1/secret-keys"
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?] = [
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
        ]

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "GET",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - returns: AgentWithVersionResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func publishAgent(
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AgentWithVersionResponse {
        let response: Response<AgentWithVersionResponse> = try await publishAgentWithHTTPInfo(
            agentId: agentId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Publish the specified agent.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentId: (path) The agentId.
    // - returns: RequestBuilder<AgentWithVersionResponse>

    open func publishAgentWithHTTPInfo(
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AgentWithVersionResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "publishAgent")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/publish"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - returns: AgentWithVersionResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func unpublishAgent(
        agentId: String,
        requestOptions: RequestOptions? = nil
    ) async throws -> AgentWithVersionResponse {
        let response: Response<AgentWithVersionResponse> = try await unpublishAgentWithHTTPInfo(
            agentId: agentId,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Unpublish the specified agent.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentId: (path) The agentId.
    // - returns: RequestBuilder<AgentWithVersionResponse>

    open func unpublishAgentWithHTTPInfo(
        agentId: String,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AgentWithVersionResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "unpublishAgent")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}/unpublish"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body: AnyCodable? = nil
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "POST",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter agentId: (path) The agentId.
    /// - parameter agentConfigUpdate: (body)
    /// - returns: AgentWithVersionResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func updateAgent(
        agentId: String,
        agentConfigUpdate: AgentConfigUpdate,
        requestOptions: RequestOptions? = nil
    ) async throws -> AgentWithVersionResponse {
        let response: Response<AgentWithVersionResponse> = try await updateAgentWithHTTPInfo(
            agentId: agentId,
            agentConfigUpdate: agentConfigUpdate,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Update the specified agent.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter agentId: (path) The agentId.
    //
    // - parameter agentConfigUpdate: (body)
    // - returns: RequestBuilder<AgentWithVersionResponse>

    open func updateAgentWithHTTPInfo(
        agentId: String,
        agentConfigUpdate: AgentConfigUpdate,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<AgentWithVersionResponse> {
        guard !agentId.isEmpty else {
            throw AlgoliaError.invalidArgument("agentId", "updateAgent")
        }

        var resourcePath = "/agent-studio/1/agents/{agentId}"
        let agentIdPreEscape = "\(APIHelper.mapValueToPathItem(agentId))"
        let agentIdPostEscape = agentIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{agentId}",
            with: agentIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = agentConfigUpdate
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "PATCH",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter applicationConfigPatch: (body)
    /// - returns: ApplicationConfigResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func updateConfiguration(
        applicationConfigPatch: ApplicationConfigPatch,
        requestOptions: RequestOptions? = nil
    ) async throws -> ApplicationConfigResponse {
        let response: Response<ApplicationConfigResponse> = try await updateConfigurationWithHTTPInfo(
            applicationConfigPatch: applicationConfigPatch,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Patch Configuration.
    // Required API Key ACLs:
    //  - logs
    //
    // - parameter applicationConfigPatch: (body)
    // - returns: RequestBuilder<ApplicationConfigResponse>

    open func updateConfigurationWithHTTPInfo(
        applicationConfigPatch: ApplicationConfigPatch,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<ApplicationConfigResponse> {
        let resourcePath = "/agent-studio/1/configuration"
        let body = applicationConfigPatch
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "PATCH",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter providerId: (path) The providerId.
    /// - parameter providerAuthenticationPatch: (body)
    /// - returns: ProviderAuthenticationResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func updateProvider(
        providerId: String,
        providerAuthenticationPatch: ProviderAuthenticationPatch,
        requestOptions: RequestOptions? = nil
    ) async throws -> ProviderAuthenticationResponse {
        let response: Response<ProviderAuthenticationResponse> = try await updateProviderWithHTTPInfo(
            providerId: providerId,
            providerAuthenticationPatch: providerAuthenticationPatch,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Update Provider.
    // Required API Key ACLs:
    //  - editSettings
    //
    // - parameter providerId: (path) The providerId.
    //
    // - parameter providerAuthenticationPatch: (body)
    // - returns: RequestBuilder<ProviderAuthenticationResponse>

    open func updateProviderWithHTTPInfo(
        providerId: String,
        providerAuthenticationPatch: ProviderAuthenticationPatch,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<ProviderAuthenticationResponse> {
        guard !providerId.isEmpty else {
            throw AlgoliaError.invalidArgument("providerId", "updateProvider")
        }

        var resourcePath = "/agent-studio/1/providers/{providerId}"
        let providerIdPreEscape = "\(APIHelper.mapValueToPathItem(providerId))"
        let providerIdPostEscape = providerIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{providerId}",
            with: providerIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = providerAuthenticationPatch
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "PATCH",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// - parameter secretKeyId: (path) The secretKeyId.
    /// - parameter secretKeyPatch: (body)
    /// - returns: SecretKeyResponse
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func updateSecretKey(
        secretKeyId: String,
        secretKeyPatch: SecretKeyPatch,
        requestOptions: RequestOptions? = nil
    ) async throws -> SecretKeyResponse {
        let response: Response<SecretKeyResponse> = try await updateSecretKeyWithHTTPInfo(
            secretKeyId: secretKeyId,
            secretKeyPatch: secretKeyPatch,
            requestOptions: requestOptions
        )

        guard let body = response.body else {
            throw AlgoliaError.missingData
        }

        return body
    }

    // Patch Secret Key.
    // Required API Key ACLs:
    //  - admin
    //
    // - parameter secretKeyId: (path) The secretKeyId.
    //
    // - parameter secretKeyPatch: (body)
    // - returns: RequestBuilder<SecretKeyResponse>

    open func updateSecretKeyWithHTTPInfo(
        secretKeyId: String,
        secretKeyPatch: SecretKeyPatch,
        requestOptions userRequestOptions: RequestOptions? = nil
    ) async throws -> Response<SecretKeyResponse> {
        guard !secretKeyId.isEmpty else {
            throw AlgoliaError.invalidArgument("secretKeyId", "updateSecretKey")
        }

        var resourcePath = "/agent-studio/1/secret-keys/{secretKeyId}"
        let secretKeyIdPreEscape = "\(APIHelper.mapValueToPathItem(secretKeyId))"
        let secretKeyIdPostEscape = secretKeyIdPreEscape
            .addingPercentEncoding(withAllowedCharacters: .urlPathAlgoliaAllowed) ?? ""
        resourcePath = resourcePath.replacingOccurrences(
            of: "{secretKeyId}",
            with: secretKeyIdPostEscape,
            options: .literal,
            range: nil
        )
        let body = secretKeyPatch
        let queryParameters: [String: Any?]? = nil

        let nillableHeaders: [String: Any?]? = nil

        let headers = APIHelper.rejectNilHeaders(nillableHeaders)

        return try await self.transporter.send(
            method: "PATCH",
            path: resourcePath,
            data: body,
            requestOptions: RequestOptions(
                headers: headers,
                queryParameters: queryParameters
            ) + userRequestOptions
        )
    }

    /// Helper: Forges a secured user token (JWT) for Agent Studio authenticated requests.
    ///
    /// - Parameters:
    ///   - secretKey: The secret key to sign the token with.
    ///   - secretKeyId: The key ID to include in the JWT header (kid).
    ///   - userId: The user identifier to include as the subject (sub) claim.
    ///   - expiresIn: The token expiration in seconds from now. Defaults to 86400 (24 hours).
    /// - Returns: The signed JWT token.
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open func forgeSecuredUserToken(
        secretKey: String,
        secretKeyId: String,
        userId: String,
        expiresIn: Int = 86400
    ) -> String {
        func base64URLEncode(_ data: Data) -> String {
            data.base64EncodedString()
                .replacingOccurrences(of: "+", with: "-")
                .replacingOccurrences(of: "/", with: "_")
                .replacingOccurrences(of: "=", with: "")
        }

        let header = base64URLEncode(Data("{\"alg\":\"HS256\",\"typ\":\"JWT\",\"kid\":\"\(secretKeyId)\"}".utf8))
        let exp = Int(Date().timeIntervalSince1970) + expiresIn
        let payload = base64URLEncode(Data("{\"sub\":\"\(userId)\",\"exp\":\(exp)}".utf8))

        let hmacHex = "\(header).\(payload)".hmac256(withKey: secretKey)
        let hmacBytes = stride(from: 0, to: hmacHex.count, by: 2).map {
            UInt8(
                hmacHex[hmacHex.index(hmacHex.startIndex, offsetBy: $0) ..< hmacHex.index(
                    hmacHex.startIndex,
                    offsetBy: $0 + 2
                )],
                radix: 16
            )!
        }
        let signature = base64URLEncode(Data(hmacBytes))

        return "\(header).\(payload).\(signature)"
    }
}
