// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct BaseRecommendSource: Codable, JSONEncodable {
    /// Index to retrieve recommendations from.
    public var indexName: String
    public var model: Model
    /// Minimum score a recommendation must have to be included.
    public var threshold: Int

    public init(indexName: String, model: Model, threshold: Int) {
        self.indexName = indexName
        self.model = model
        self.threshold = threshold
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case indexName
        case model
        case threshold
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.indexName, forKey: .indexName)
        try container.encode(self.model, forKey: .model)
        try container.encode(self.threshold, forKey: .threshold)
    }
}

extension BaseRecommendSource: Equatable {}

extension BaseRecommendSource: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.indexName.hashValue)
        hasher.combine(self.model.hashValue)
        hasher.combine(self.threshold.hashValue)
    }
}
