// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct CompositionMultipleBatchResponse: Codable, JSONEncodable {
    /// Task IDs. One for each index.
    public var taskID: [String: Int64]

    public init(taskID: [String: Int64]) {
        self.taskID = taskID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case taskID
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.taskID, forKey: .taskID)
    }
}

extension CompositionMultipleBatchResponse: Equatable {
    public static func ==(lhs: CompositionMultipleBatchResponse, rhs: CompositionMultipleBatchResponse) -> Bool {
        lhs.taskID == rhs.taskID
    }
}

extension CompositionMultipleBatchResponse: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.taskID.hashValue)
    }
}
