// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Widgets returned from any rules that are applied to the current search.
public struct CompositionWidgets: Codable, JSONEncodable {
    /// Banners defined in the Merchandising Studio for a given search.
    public var banners: [CompositionBanner]?
    public var resultCard: CompositionResultCard?

    public init(banners: [CompositionBanner]? = nil, resultCard: CompositionResultCard? = nil) {
        self.banners = banners
        self.resultCard = resultCard
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case banners
        case resultCard
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.banners, forKey: .banners)
        try container.encodeIfPresent(self.resultCard, forKey: .resultCard)
    }
}

extension CompositionWidgets: Equatable {}

extension CompositionWidgets: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.banners?.hashValue)
        hasher.combine(self.resultCard?.hashValue)
    }
}
