// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Effect of the rule.
public struct CompositionRuleConsequence: Codable, JSONEncodable {
    public var behavior: CompositionBehavior

    public init(behavior: CompositionBehavior) {
        self.behavior = behavior
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case behavior
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.behavior, forKey: .behavior)
    }
}

extension CompositionRuleConsequence: Equatable {
    public static func ==(lhs: CompositionRuleConsequence, rhs: CompositionRuleConsequence) -> Bool {
        lhs.behavior == rhs.behavior
    }
}

extension CompositionRuleConsequence: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.behavior.hashValue)
    }
}
