// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Deduplication configures the methods used to resolve duplicate items between main search results and injected group
/// results.
public struct Deduplication: Codable, JSONEncodable {
    public var positioning: DedupPositioning

    public init(positioning: DedupPositioning) {
        self.positioning = positioning
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case positioning
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.positioning, forKey: .positioning)
    }
}

extension Deduplication: Equatable {
    public static func ==(lhs: Deduplication, rhs: Deduplication) -> Bool {
        lhs.positioning == rhs.positioning
    }
}

extension Deduplication: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.positioning.hashValue)
    }
}
