// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Injected items will originate from a request to an external provider configuration.
public struct InjectedItemExternalProviderSource: Codable, JSONEncodable {
    public var externalProvider: InjectedItemExternalProvider

    public init(externalProvider: InjectedItemExternalProvider) {
        self.externalProvider = externalProvider
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case externalProvider
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.externalProvider, forKey: .externalProvider)
    }
}

extension InjectedItemExternalProviderSource: Equatable {}

extension InjectedItemExternalProviderSource: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.externalProvider.hashValue)
    }
}
