// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Main defines the organic result set of the injection.
public struct InjectionMain: Codable, JSONEncodable {
    public var source: InjectionMainSource?

    public init(source: InjectionMainSource? = nil) {
        self.source = source
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case source
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.source, forKey: .source)
    }
}

extension InjectionMain: Equatable {
    public static func ==(lhs: InjectionMain, rhs: InjectionMain) -> Bool {
        lhs.source == rhs.source
    }
}

extension InjectionMain: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.source?.hashValue)
    }
}
