// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct ResultsInjectedItemInfoResponse: Codable, JSONEncodable {
    public var key: String
    public var appliedRules: [ResultsInjectedItemAppliedRulesInfoResponse]?

    public init(key: String, appliedRules: [ResultsInjectedItemAppliedRulesInfoResponse]? = nil) {
        self.key = key
        self.appliedRules = appliedRules
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case appliedRules
    }

    public var additionalProperties: [String: AnyCodable] = [:]

    public subscript(key: String) -> AnyCodable? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            self.additionalProperties[key] = newValue
        }
    }

    public init(from dictionary: [String: AnyCodable]) throws {
        guard let key = dictionary["key"]?.value as? String else {
            throw GenericError(description: "Failed to cast")
        }
        self.key = key
        self.appliedRules = dictionary["appliedRules"]?.value as? [ResultsInjectedItemAppliedRulesInfoResponse]

        for (key, value) in dictionary {
            switch key {
            case "key", "appliedRules":
                continue
            default:
                self.additionalProperties[key] = value
            }
        }
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.key, forKey: .key)
        try container.encodeIfPresent(self.appliedRules, forKey: .appliedRules)
        var additionalPropertiesContainer = encoder.container(keyedBy: String.self)
        try additionalPropertiesContainer.encodeMap(self.additionalProperties)
    }

    // Decodable protocol methods

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        self.key = try container.decode(String.self, forKey: .key)
        self.appliedRules = try container.decodeIfPresent(
            [ResultsInjectedItemAppliedRulesInfoResponse].self,
            forKey: .appliedRules
        )
        var nonAdditionalPropertyKeys = Set<String>()
        nonAdditionalPropertyKeys.insert("key")
        nonAdditionalPropertyKeys.insert("appliedRules")
        let additionalPropertiesContainer = try decoder.container(keyedBy: String.self)
        self.additionalProperties = try additionalPropertiesContainer.decodeMap(
            AnyCodable.self,
            excludedKeys: nonAdditionalPropertyKeys
        )
    }
}

extension ResultsInjectedItemInfoResponse: Equatable {
    public static func ==(lhs: ResultsInjectedItemInfoResponse, rhs: ResultsInjectedItemInfoResponse) -> Bool {
        lhs.key == rhs.key &&
            lhs.appliedRules == rhs.appliedRules
            && lhs.additionalProperties == rhs.additionalProperties
    }
}

extension ResultsInjectedItemInfoResponse: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.key.hashValue)
        hasher.combine(self.appliedRules?.hashValue)
        hasher.combine(self.additionalProperties.hashValue)
    }
}
