# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

desc "Test library"
lane :test do
  sh("cd ..; swift test")
end

desc "Lint library"
lane :lint do |args|
  swiftlint(
    mode: :lint,
    raise_if_swiftlint_error: true,
    strict: true
  )
end
