// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

#if canImport(AnyCodable)
    import AnyCodable
#endif
import Core
import Foundation

public enum RecommendModels: String, Codable, CaseIterable {
    case relatedProducts = "related-products"
    case boughtTogether = "bought-together"
    case trendingFacets = "trending-facets"
    case trendingItems = "trending-items"
}
