// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public enum RecommendHighlightResult: Codable, JSONEncodable, AbstractEncodable {
    case dictionaryOfStringToRecommendHighlightResult([String: RecommendHighlightResult])
    case recommendHighlightResultOption(RecommendHighlightResultOption)
    case dictionaryOfStringToRecommendHighlightResultOption([String: RecommendHighlightResultOption])
    case arrayOfRecommendHighlightResultOption([RecommendHighlightResultOption])

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .dictionaryOfStringToRecommendHighlightResult(value):
            try container.encode(value)
        case let .recommendHighlightResultOption(value):
            try container.encode(value)
        case let .dictionaryOfStringToRecommendHighlightResultOption(value):
            try container.encode(value)
        case let .arrayOfRecommendHighlightResultOption(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode([String: RecommendHighlightResult].self) {
            self = .dictionaryOfStringToRecommendHighlightResult(value)
        } else if let value = try? container.decode(RecommendHighlightResultOption.self) {
            self = .recommendHighlightResultOption(value)
        } else if let value = try? container.decode([String: RecommendHighlightResultOption].self) {
            self = .dictionaryOfStringToRecommendHighlightResultOption(value)
        } else if let value = try? container.decode([RecommendHighlightResultOption].self) {
            self = .arrayOfRecommendHighlightResultOption(value)
        } else {
            throw DecodingError.typeMismatch(
                Self.Type.self,
                .init(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unable to decode instance of RecommendHighlightResult"
                )
            )
        }
    }

    public func GetActualInstance() -> Encodable {
        switch self {
        case let .dictionaryOfStringToRecommendHighlightResult(value):
            value as [String: RecommendHighlightResult]
        case let .recommendHighlightResultOption(value):
            value as RecommendHighlightResultOption
        case let .dictionaryOfStringToRecommendHighlightResultOption(value):
            value as [String: RecommendHighlightResultOption]
        case let .arrayOfRecommendHighlightResultOption(value):
            value as [RecommendHighlightResultOption]
        }
    }
}

extension RecommendHighlightResult: Equatable {}
extension RecommendHighlightResult: Hashable {}
