// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public enum EventsItems: Codable, JSONEncodable, AbstractEncodable, Hashable {
    case addedToCartObjectIDs(AddedToCartObjectIDs)
    case addedToCartObjectIDsAfterSearch(AddedToCartObjectIDsAfterSearch)
    case clickedFilters(ClickedFilters)
    case clickedObjectIDs(ClickedObjectIDs)
    case clickedObjectIDsAfterSearch(ClickedObjectIDsAfterSearch)
    case convertedFilters(ConvertedFilters)
    case convertedObjectIDs(ConvertedObjectIDs)
    case convertedObjectIDsAfterSearch(ConvertedObjectIDsAfterSearch)
    case purchasedObjectIDs(PurchasedObjectIDs)
    case purchasedObjectIDsAfterSearch(PurchasedObjectIDsAfterSearch)
    case viewedFilters(ViewedFilters)
    case viewedObjectIDs(ViewedObjectIDs)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .addedToCartObjectIDs(value):
            try container.encode(value)
        case let .addedToCartObjectIDsAfterSearch(value):
            try container.encode(value)
        case let .clickedFilters(value):
            try container.encode(value)
        case let .clickedObjectIDs(value):
            try container.encode(value)
        case let .clickedObjectIDsAfterSearch(value):
            try container.encode(value)
        case let .convertedFilters(value):
            try container.encode(value)
        case let .convertedObjectIDs(value):
            try container.encode(value)
        case let .convertedObjectIDsAfterSearch(value):
            try container.encode(value)
        case let .purchasedObjectIDs(value):
            try container.encode(value)
        case let .purchasedObjectIDsAfterSearch(value):
            try container.encode(value)
        case let .viewedFilters(value):
            try container.encode(value)
        case let .viewedObjectIDs(value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(AddedToCartObjectIDs.self) {
            self = .addedToCartObjectIDs(value)
        } else if let value = try? container.decode(AddedToCartObjectIDsAfterSearch.self) {
            self = .addedToCartObjectIDsAfterSearch(value)
        } else if let value = try? container.decode(ClickedFilters.self) {
            self = .clickedFilters(value)
        } else if let value = try? container.decode(ClickedObjectIDs.self) {
            self = .clickedObjectIDs(value)
        } else if let value = try? container.decode(ClickedObjectIDsAfterSearch.self) {
            self = .clickedObjectIDsAfterSearch(value)
        } else if let value = try? container.decode(ConvertedFilters.self) {
            self = .convertedFilters(value)
        } else if let value = try? container.decode(ConvertedObjectIDs.self) {
            self = .convertedObjectIDs(value)
        } else if let value = try? container.decode(ConvertedObjectIDsAfterSearch.self) {
            self = .convertedObjectIDsAfterSearch(value)
        } else if let value = try? container.decode(PurchasedObjectIDs.self) {
            self = .purchasedObjectIDs(value)
        } else if let value = try? container.decode(PurchasedObjectIDsAfterSearch.self) {
            self = .purchasedObjectIDsAfterSearch(value)
        } else if let value = try? container.decode(ViewedFilters.self) {
            self = .viewedFilters(value)
        } else if let value = try? container.decode(ViewedObjectIDs.self) {
            self = .viewedObjectIDs(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of EventsItems"))
        }
    }

    public func GetActualInstance() -> Encodable {
        switch self {
        case let .addedToCartObjectIDs(value):
            return value as AddedToCartObjectIDs
        case let .addedToCartObjectIDsAfterSearch(value):
            return value as AddedToCartObjectIDsAfterSearch
        case let .clickedFilters(value):
            return value as ClickedFilters
        case let .clickedObjectIDs(value):
            return value as ClickedObjectIDs
        case let .clickedObjectIDsAfterSearch(value):
            return value as ClickedObjectIDsAfterSearch
        case let .convertedFilters(value):
            return value as ConvertedFilters
        case let .convertedObjectIDs(value):
            return value as ConvertedObjectIDs
        case let .convertedObjectIDsAfterSearch(value):
            return value as ConvertedObjectIDsAfterSearch
        case let .purchasedObjectIDs(value):
            return value as PurchasedObjectIDs
        case let .purchasedObjectIDsAfterSearch(value):
            return value as PurchasedObjectIDsAfterSearch
        case let .viewedFilters(value):
            return value as ViewedFilters
        case let .viewedObjectIDs(value):
            return value as ViewedObjectIDs
        }
    }
}
