// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct AbtestingAbTestsVariantSearchParams: Codable, JSONEncodable {
    /// Index name of the A/B test variant (case-sensitive).
    public var index: String
    /// Percentage of search requests each variant receives.
    public var trafficPercentage: Int
    /// Description for this variant.
    public var description: String?
    public var customSearchParameters: AnyCodable

    public init(index: String, trafficPercentage: Int, description: String? = nil, customSearchParameters: AnyCodable) {
        self.index = index
        self.trafficPercentage = trafficPercentage
        self.description = description
        self.customSearchParameters = customSearchParameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case trafficPercentage
        case description
        case customSearchParameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.index, forKey: .index)
        try container.encode(self.trafficPercentage, forKey: .trafficPercentage)
        try container.encodeIfPresent(self.description, forKey: .description)
        try container.encode(self.customSearchParameters, forKey: .customSearchParameters)
    }
}

extension AbtestingAbTestsVariantSearchParams: Equatable {
    public static func ==(lhs: AbtestingAbTestsVariantSearchParams, rhs: AbtestingAbTestsVariantSearchParams) -> Bool {
        lhs.index == rhs.index &&
            lhs.trafficPercentage == rhs.trafficPercentage &&
            lhs.description == rhs.description &&
            lhs.customSearchParameters == rhs.customSearchParameters
    }
}

extension AbtestingAbTestsVariantSearchParams: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.index.hashValue)
        hasher.combine(self.trafficPercentage.hashValue)
        hasher.combine(self.description?.hashValue)
        hasher.combine(self.customSearchParameters.hashValue)
    }
}
