// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// Metric for which you want to detect the smallest relative difference.
public enum EffectMetric: String, Codable, CaseIterable {
    case addToCartRate
    case clickThroughRate
    case conversionRate
    case purchaseRate
}

extension EffectMetric: Hashable {}
