// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Core
import Foundation

#if canImport(AnyCodable)
  import AnyCodable
#endif

public struct IndexingTimeResponseMetrics: Codable, JSONEncodable, Hashable {

  public var indexing: [String: [TimeInner]]?

  public init(indexing: [String: [TimeInner]]? = nil) {
    self.indexing = indexing
  }

  public enum CodingKeys: String, CodingKey, CaseIterable {
    case indexing
  }

  // Encodable protocol methods

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(indexing, forKey: .indexing)
  }
}
