// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct IndexingTimeResponse: Codable, JSONEncodable {
    public var metrics: IndexingMetric?

    public init(metrics: IndexingMetric? = nil) {
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metrics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.metrics, forKey: .metrics)
    }
}

extension IndexingTimeResponse: Equatable {
    public static func ==(lhs: IndexingTimeResponse, rhs: IndexingTimeResponse) -> Bool {
        lhs.metrics == rhs.metrics
    }
}

extension IndexingTimeResponse: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.metrics?.hashValue)
    }
}
