// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

public struct DistributionPayload: Codable, JSONEncodable {
    /// Default domain propagated to entries that omit their own.
    public var domain: String?
    /// Histogram specifications.
    public var distributions: [DistributionDefinition]
    /// Filter conditions.
    public var filters: [FilterDefinition]?
    /// Literal values referenced by the query.
    public var parameters: [ParameterDefinition]

    public init(
        domain: String? = nil,
        distributions: [DistributionDefinition],
        filters: [FilterDefinition]? = nil,
        parameters: [ParameterDefinition]
    ) {
        self.domain = domain
        self.distributions = distributions
        self.filters = filters
        self.parameters = parameters
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case distributions
        case filters
        case parameters
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.domain, forKey: .domain)
        try container.encode(self.distributions, forKey: .distributions)
        try container.encodeIfPresent(self.filters, forKey: .filters)
        try container.encode(self.parameters, forKey: .parameters)
    }
}

extension DistributionPayload: Equatable {}

extension DistributionPayload: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.domain?.hashValue)
        hasher.combine(self.distributions.hashValue)
        hasher.combine(self.filters?.hashValue)
        hasher.combine(self.parameters.hashValue)
    }
}
