// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

public struct GetRevenue: Codable, JSONEncodable {
    /// Revenue associated with this search: broken down by currency.
    public var currencies: [String: CurrencyCode]
    /// Daily revenue.
    public var dates: [DailyRevenue]

    public init(currencies: [String: CurrencyCode], dates: [DailyRevenue]) {
        self.currencies = currencies
        self.dates = dates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case currencies
        case dates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.currencies, forKey: .currencies)
        try container.encode(self.dates, forKey: .dates)
    }
}

extension GetRevenue: Equatable {
    public static func ==(lhs: GetRevenue, rhs: GetRevenue) -> Bool {
        lhs.currencies == rhs.currencies &&
            lhs.dates == rhs.dates
    }
}

extension GetRevenue: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.currencies.hashValue)
        hasher.combine(self.dates.hashValue)
    }
}
