// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

#if canImport(AnyCodable)
    import AnyCodable
#endif
import Core
import Foundation

public struct GetTopFiltersNoResultsValue: Codable, JSONEncodable, Hashable {
    /// Attribute name.
    public var attribute: String
    /// Operator.
    public var `operator`: String
    /// Attribute value.
    public var value: String

    public init(attribute: String, `operator`: String, value: String) {
        self.attribute = attribute
        self.`operator` = `operator`
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribute
        case `operator`
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.attribute, forKey: .attribute)
        try container.encode(self.`operator`, forKey: .`operator`)
        try container.encode(self.value, forKey: .value)
    }
}
