// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(Core)
    import Core
#endif

/// Attribute by which to order the response items.  If the `clickAnalytics` parameter is false, only `searchCount` is
/// available.
public enum OrderBy: String, Codable, CaseIterable {
    case searchCount
    case clickThroughRate
    case conversionRate
    case averageClickPosition
}

extension OrderBy: Hashable {}
