// Code generated by OpenAPI Generator (https://openapi-generator.tech), manual changes will be lost - read more on
// https://github.com/algolia/api-clients-automation. DO NOT EDIT.

import Foundation
#if canImport(AlgoliaCore)
    import AlgoliaCore
#endif

/// When `groupBy` is set, `orderBy` is required.
public struct TablePayload: Codable, JSONEncodable {
    /// Default domain propagated to entries that omit their own.
    public var domain: String?
    /// Fields to aggregate.
    public var metrics: [FieldReference]
    /// Fields to split rows by.
    public var groupBy: [FieldReference]?
    /// Filter conditions.
    public var filters: [FilterDefinition]?
    /// Literal values referenced by the query.
    public var parameters: [ParameterDefinition]
    /// Sort specification. Required when `groupBy` is set.
    public var orderBy: [OrderDefinition]?
    /// Maximum number of rows to return.
    public var limit: Int?
    /// Number of rows to skip.
    public var offset: Int?

    public init(
        domain: String? = nil,
        metrics: [FieldReference],
        groupBy: [FieldReference]? = nil,
        filters: [FilterDefinition]? = nil,
        parameters: [ParameterDefinition],
        orderBy: [OrderDefinition]? = nil,
        limit: Int? = nil,
        offset: Int? = nil
    ) {
        self.domain = domain
        self.metrics = metrics
        self.groupBy = groupBy
        self.filters = filters
        self.parameters = parameters
        self.orderBy = orderBy
        self.limit = limit
        self.offset = offset
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case metrics
        case groupBy
        case filters
        case parameters
        case orderBy
        case limit
        case offset
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.domain, forKey: .domain)
        try container.encode(self.metrics, forKey: .metrics)
        try container.encodeIfPresent(self.groupBy, forKey: .groupBy)
        try container.encodeIfPresent(self.filters, forKey: .filters)
        try container.encode(self.parameters, forKey: .parameters)
        try container.encodeIfPresent(self.orderBy, forKey: .orderBy)
        try container.encodeIfPresent(self.limit, forKey: .limit)
        try container.encodeIfPresent(self.offset, forKey: .offset)
    }
}

extension TablePayload: Equatable {}

extension TablePayload: Hashable {
    public func hash(into hasher: inout Hasher) {
        hasher.combine(self.domain?.hashValue)
        hasher.combine(self.metrics.hashValue)
        hasher.combine(self.groupBy?.hashValue)
        hasher.combine(self.filters?.hashValue)
        hasher.combine(self.parameters.hashValue)
        hasher.combine(self.orderBy?.hashValue)
        hasher.combine(self.limit?.hashValue)
        hasher.combine(self.offset?.hashValue)
    }
}
