name: Changelog
on: [push]
jobs:
  test-changelog:
    runs-on: macos-11
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set release type environment
        run: |
          echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $GITHUB_ENV
      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Install polyglot
        run: |
          make install
          export PATH="$GOPATH/bin:$PATH"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get tags
        run: |
          git fetch --tags origin
          git tag --list
          git tag -l
          echo $(git tag -l)
          echo "test"
      - name: Test changelog generation
        run: |
          echo "before"
          echo $(git tag -l)
          echo "after"
          polyglot changelog -v -d 8.15.0