name: Changelog
on: [push]
jobs:
  test-changelog:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set release type environment
        run: |
          echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Install polyglot
        run: |
          make install
          export PATH="$GOPATH/bin:$PATH"
      - name: Test changelog generation
        run: |
          polyglot changelog -v -d 8.15.0