name: Deployment
on: 
  push:
    tags: 
     - patcht
     - minort
     - majort
jobs:
  deploy:
    runs-on: macos-11
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_TYPE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_TYPE
          echo ${{ env.RELEASE_TYPE }}
      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Install polyglot
        run: |
          echo $GOPATH
          echo $PATH
          make install
          export PATH="$GOPATH/bin:$PATH"
          polyglot version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
          bundler-cache: true
      - uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'deploy'
          options: '{ "type": "${{ env.RELEASE_TYPE }}" }'
          
