name: Swift Format Check

on: [pull_request]

jobs:
  format-check:
    name: Swift Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: mtgto/swift-format-action@main
        with:
          configuration_file: .swift-format
          all_files: false
          max_warnings: -1
