name: Swift Format Check

on: [pull_request]

jobs:
  format-check:
    name: Swift Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: 5.8

      - name: Install Swift Format
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
          swift package install swift-format --force

      - name: Run Swift Format Check
        run: |
          swift-format lint ./Sources -srp
