name: Tests on Linux

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift_version }}

      - name: Build and test
        run: |
          swift build
          swift test --enable-test-discovery

    strategy:
      matrix:
        swift_version:
          - "5.8"
