name: Release package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish
    runs-on: ubuntu-22.04
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.7
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Publish on CocoaPods
        run: |
          set -eo pipefail
          pod trunk push --allow-warnings --verbose AlgoliaSearchClient.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
