name: Release package

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish
    runs-on: ubuntu-22.04
    if: "startsWith(github.event.head_commit.message, 'chore: release')"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Install Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: 4.0.6
          bundler-cache: true

      - name: Install CocoaPods
        run: gem install cocoapods

      - name: Publish on CocoaPods
        run: |
          set -eo pipefail
          pod trunk push --allow-warnings --verbose AlgoliaSearchClient.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
