name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode version
        run: sudo xcode-select -p
      - run: ls /Applications 
      - run: sudo xcode-select -s '/Applications/Xcode_13.2.app/Contents/Developer'
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test